name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: TestMAQWebApp  # set this to the name of your Azure Web App
  ACR_REPO_NAME: testwebapp

on:
  push:
    branches: [ "AnujMAQ-patch-1" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        run: |
          docker build . -t ${{ secrets.ACR_ENDPOINT }}/${{ env.ACR_REPO_NAME }}:${{ github.sha }}
          docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.ACR_REPO_NAME }}:${{ github.sha }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPN_CREDENTIALS }}
        
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          acrName: blueyonder
          containerAppName: testcontainerapp
          resourceGroup: BlueYonder
          imageToDeploy: ${{ secrets.ACR_ENDPOINT }}/${{ env.ACR_REPO_NAME }}:${{ github.sha }}
